### ISSUE TITLE
Further Hardware drivers

### ISSUE THREAD

**Issue by jankap** [DISTORTEC/distortos#38]
Hi,

great work, thank you!

I wonder if you aim to implement further hardware drivers / HAL or similar, or is this development focussed on the RTOS "only"?

Thank you very much,
Jan

**Comment by FreddieChopin** [comment]
> I wonder if you aim to implement further hardware drivers / HAL or similar, or is this development focussed on the RTOS "only"?

I would like this project to become a complete framework, which means that both RTOS and HAL are important (; As you see for now there are very little drivers implemented, but this is still a young project, so definitely there are more to come. Pull-requests are of course welcome!

Regards,
FCh
